apiVersion: v1
kind: ReplicationController
metadata:
  name: java-microservice-api-1.0-rc
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app-name: java-microservice-api
        app-version: "1.0"
    spec:
      containers:
      - name: myapi
        image: nextmetaphor/java-microservice-api:1.0
        ports:
        - containerPort: 8080
