apiVersion: v1
kind: Service
metadata:
  name: java-microservice-api-svc
spec:
  type: NodePort
  selector:
    app-name: java-microservice-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30286